//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NucleusExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicYear
    {
        public decimal AcademicYearID { get; set; }
        public string AcademicYear1 { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string SMSDBAlias { get; set; }
        public string FirstDayOfAcademicYear { get; set; }
        public Nullable<bool> IsHRPlanningDone { get; set; }
        public Nullable<bool> IsStaffCalendarCreated { get; set; }
    }
}
