//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NucleusExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA_ExamCommentScoreMaster
    {
        public int CommentID { get; set; }
        public Nullable<decimal> ExamID { get; set; }
        public string QID { get; set; }
        public Nullable<decimal> StudentID { get; set; }
        public string Comment { get; set; }
        public string ScoreType { get; set; }
        public string ObtainScore { get; set; }
        public Nullable<decimal> CommentBy { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<decimal> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
