//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NucleusExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA_ExamAnswerMaster
    {
        public decimal AnswerID { get; set; }
        public string QID { get; set; }
        public Nullable<decimal> ExamID { get; set; }
        public Nullable<decimal> StudentID { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string Answer { get; set; }
        public Nullable<int> QuestionNumber { get; set; }
    }
}
