//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NucleusExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA_ExamMaster
    {
        public decimal ExamID { get; set; }
        public string ExamName { get; set; }
        public Nullable<decimal> GradeID { get; set; }
        public Nullable<decimal> AcademicYearID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<bool> ISExamCode { get; set; }
        public string ExamCode { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public string ExamURL { get; set; }
        public Nullable<bool> ISActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<decimal> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
