//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NucleusExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA_QuestionMaster
    {
        public int QuestionID { get; set; }
        public Nullable<decimal> ExamID { get; set; }
        public string QuestionType { get; set; }
        public Nullable<int> QuestionMarks { get; set; }
        public string Question { get; set; }
        public Nullable<decimal> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<decimal> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
