//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NucleusExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA_StudentEnrollment
    {
        public decimal ES_EnrollmentID { get; set; }
        public Nullable<decimal> StudentID { get; set; }
        public Nullable<decimal> ExamID { get; set; }
        public Nullable<decimal> GradeID { get; set; }
        public Nullable<decimal> SectionID { get; set; }
        public Nullable<System.DateTime> ExamStartTime { get; set; }
        public Nullable<System.DateTime> ExamEndTime { get; set; }
        public Nullable<System.DateTime> ActualStartTime { get; set; }
        public Nullable<System.DateTime> ActualEndTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<bool> ISExamEnable { get; set; }
        public Nullable<bool> ISExamFinish { get; set; }
        public Nullable<decimal> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
