//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NucleusExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA_StaffRights
    {
        public int RightsID { get; set; }
        public Nullable<decimal> StaffID { get; set; }
        public Nullable<bool> ISRights { get; set; }
        public Nullable<System.DateTime> GivenDate { get; set; }
        public Nullable<bool> ISAdminRights { get; set; }
        public Nullable<decimal> AssignBy { get; set; }
    }
}
