//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NucleusExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class EA_TeacherEnrollment
    {
        public decimal ET_EnrollmentID { get; set; }
        public Nullable<decimal> StaffID { get; set; }
        public Nullable<decimal> ExamID { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
    }
}
