//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NucleusExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeSectionMapping
    {
        public decimal GradeSectionMappingID { get; set; }
        public decimal GradeID { get; set; }
        public decimal SectionID { get; set; }
    }
}
