//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NucleusExams
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EA_ExamMaster> EA_ExamMaster { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<WorkingStaffList> WorkingStaffList { get; set; }
        public virtual DbSet<AcademicYear> AcademicYear { get; set; }
        public virtual DbSet<GradeSection> GradeSection { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<GradeSectionMapping> GradeSectionMapping { get; set; }
        public virtual DbSet<EA_StudentEnrollment> EA_StudentEnrollment { get; set; }
        public virtual DbSet<EA_TeacherEnrollment> EA_TeacherEnrollment { get; set; }
        public virtual DbSet<EA_ExamAnswerMaster> EA_ExamAnswerMaster { get; set; }
        public virtual DbSet<StudentCurrentGradeSectionDetails> StudentCurrentGradeSectionDetails { get; set; }
        public virtual DbSet<EA_ExamCommentScoreMaster> EA_ExamCommentScoreMaster { get; set; }
        public virtual DbSet<EA_QuestionMaster> EA_QuestionMaster { get; set; }
        public virtual DbSet<EA_StaffRights> EA_StaffRights { get; set; }
        public virtual DbSet<EA_OptionMaster> EA_OptionMaster { get; set; }
        public virtual DbSet<EA_ExamRightsMaster> EA_ExamRightsMaster { get; set; }
    
        public virtual int ea_spiEA_ExamMaster(string examName, Nullable<decimal> gradeID, string subjectName, Nullable<int> duration, Nullable<decimal> createdBy, Nullable<bool> iSExamCode, string examCode, Nullable<System.DateTime> examDate, string examURL)
        {
            var examNameParameter = examName != null ?
                new ObjectParameter("ExamName", examName) :
                new ObjectParameter("ExamName", typeof(string));
    
            var gradeIDParameter = gradeID.HasValue ?
                new ObjectParameter("GradeID", gradeID) :
                new ObjectParameter("GradeID", typeof(decimal));
    
            var subjectNameParameter = subjectName != null ?
                new ObjectParameter("SubjectName", subjectName) :
                new ObjectParameter("SubjectName", typeof(string));
    
            var durationParameter = duration.HasValue ?
                new ObjectParameter("Duration", duration) :
                new ObjectParameter("Duration", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(decimal));
    
            var iSExamCodeParameter = iSExamCode.HasValue ?
                new ObjectParameter("ISExamCode", iSExamCode) :
                new ObjectParameter("ISExamCode", typeof(bool));
    
            var examCodeParameter = examCode != null ?
                new ObjectParameter("ExamCode", examCode) :
                new ObjectParameter("ExamCode", typeof(string));
    
            var examDateParameter = examDate.HasValue ?
                new ObjectParameter("ExamDate", examDate) :
                new ObjectParameter("ExamDate", typeof(System.DateTime));
    
            var examURLParameter = examURL != null ?
                new ObjectParameter("ExamURL", examURL) :
                new ObjectParameter("ExamURL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ea_spiEA_ExamMaster", examNameParameter, gradeIDParameter, subjectNameParameter, durationParameter, createdByParameter, iSExamCodeParameter, examCodeParameter, examDateParameter, examURLParameter);
        }
    
        public virtual int ea_spdEA_ExamMaster(Nullable<decimal> examID)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ea_spdEA_ExamMaster", examIDParameter);
        }
    
        public virtual ObjectResult<ea_spgEA_ExamMaster_Result> ea_spgEA_ExamMaster()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spgEA_ExamMaster_Result>("ea_spgEA_ExamMaster");
        }
    
        public virtual int ea_spuEA_ExamMaster(Nullable<decimal> examID, string examName, Nullable<decimal> gradeID, string subjectName, Nullable<int> duration, Nullable<decimal> createdBy, Nullable<System.DateTime> examDate, string examURL)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            var examNameParameter = examName != null ?
                new ObjectParameter("ExamName", examName) :
                new ObjectParameter("ExamName", typeof(string));
    
            var gradeIDParameter = gradeID.HasValue ?
                new ObjectParameter("GradeID", gradeID) :
                new ObjectParameter("GradeID", typeof(decimal));
    
            var subjectNameParameter = subjectName != null ?
                new ObjectParameter("SubjectName", subjectName) :
                new ObjectParameter("SubjectName", typeof(string));
    
            var durationParameter = duration.HasValue ?
                new ObjectParameter("Duration", duration) :
                new ObjectParameter("Duration", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(decimal));
    
            var examDateParameter = examDate.HasValue ?
                new ObjectParameter("ExamDate", examDate) :
                new ObjectParameter("ExamDate", typeof(System.DateTime));
    
            var examURLParameter = examURL != null ?
                new ObjectParameter("ExamURL", examURL) :
                new ObjectParameter("ExamURL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ea_spuEA_ExamMaster", examIDParameter, examNameParameter, gradeIDParameter, subjectNameParameter, durationParameter, createdByParameter, examDateParameter, examURLParameter);
        }
    
        public virtual ObjectResult<spgStudentCurrentGradeSectionDetailsBySectionID_Result> spgStudentCurrentGradeSectionDetailsBySectionID(string sectionID)
        {
            var sectionIDParameter = sectionID != null ?
                new ObjectParameter("SectionID", sectionID) :
                new ObjectParameter("SectionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spgStudentCurrentGradeSectionDetailsBySectionID_Result>("spgStudentCurrentGradeSectionDetailsBySectionID", sectionIDParameter);
        }
    
        public virtual int ea_spiEA_StudentEnrollment(Nullable<decimal> studentID, Nullable<decimal> examID, Nullable<decimal> staffID)
        {
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(decimal));
    
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            var staffIDParameter = staffID.HasValue ?
                new ObjectParameter("StaffID", staffID) :
                new ObjectParameter("StaffID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ea_spiEA_StudentEnrollment", studentIDParameter, examIDParameter, staffIDParameter);
        }
    
        public virtual int ea_spiEA_TeacherEnrollment(Nullable<decimal> staffID, Nullable<decimal> examID, Nullable<decimal> entryBy)
        {
            var staffIDParameter = staffID.HasValue ?
                new ObjectParameter("StaffID", staffID) :
                new ObjectParameter("StaffID", typeof(decimal));
    
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            var entryByParameter = entryBy.HasValue ?
                new ObjectParameter("EntryBy", entryBy) :
                new ObjectParameter("EntryBy", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ea_spiEA_TeacherEnrollment", staffIDParameter, examIDParameter, entryByParameter);
        }
    
        public virtual int ea_spiEA_ExamAnswerMaster(string qID, Nullable<decimal> studentID, string answer, Nullable<decimal> examID)
        {
            var qIDParameter = qID != null ?
                new ObjectParameter("QID", qID) :
                new ObjectParameter("QID", typeof(string));
    
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(decimal));
    
            var answerParameter = answer != null ?
                new ObjectParameter("Answer", answer) :
                new ObjectParameter("Answer", typeof(string));
    
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ea_spiEA_ExamAnswerMaster", qIDParameter, studentIDParameter, answerParameter, examIDParameter);
        }
    
        public virtual ObjectResult<string> ea_spgEA_ExamAnswerMasterByQuestionIDStudentID(string qID, Nullable<decimal> studentID, Nullable<decimal> examID)
        {
            var qIDParameter = qID != null ?
                new ObjectParameter("QID", qID) :
                new ObjectParameter("QID", typeof(string));
    
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(decimal));
    
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ea_spgEA_ExamAnswerMasterByQuestionIDStudentID", qIDParameter, studentIDParameter, examIDParameter);
        }
    
        public virtual ObjectResult<ea_spgEA_ExamAnswerMasterByStudentIDExamID_Result> ea_spgEA_ExamAnswerMasterByStudentIDExamID(Nullable<decimal> studentID, Nullable<decimal> examID)
        {
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(decimal));
    
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spgEA_ExamAnswerMasterByStudentIDExamID_Result>("ea_spgEA_ExamAnswerMasterByStudentIDExamID", studentIDParameter, examIDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> ea_spgStudentIDByMD5HashCode(string mD5HashCode)
        {
            var mD5HashCodeParameter = mD5HashCode != null ?
                new ObjectParameter("MD5HashCode", mD5HashCode) :
                new ObjectParameter("MD5HashCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("ea_spgStudentIDByMD5HashCode", mD5HashCodeParameter);
        }
    
        public virtual int ea_spdEA_StudentEnrollment(Nullable<decimal> studentID, Nullable<decimal> examID)
        {
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(decimal));
    
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ea_spdEA_StudentEnrollment", studentIDParameter, examIDParameter);
        }
    
        public virtual int ea_spuEA_StudentEnrollmentDisableByStudentIDExamID(Nullable<decimal> studentID, Nullable<decimal> examID)
        {
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(decimal));
    
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ea_spuEA_StudentEnrollmentDisableByStudentIDExamID", studentIDParameter, examIDParameter);
        }
    
        public virtual int ea_spuEA_StudentEnrollmentEnableByStudentIDExamID(Nullable<decimal> studentID, Nullable<decimal> examID)
        {
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(decimal));
    
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ea_spuEA_StudentEnrollmentEnableByStudentIDExamID", studentIDParameter, examIDParameter);
        }
    
        public virtual ObjectResult<ea_spgEA_StudentEnrollmentCheckExamActiveByStudentIDExamID_Result> ea_spgEA_StudentEnrollmentCheckExamActiveByStudentIDExamID(Nullable<decimal> examID, Nullable<decimal> studentID)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spgEA_StudentEnrollmentCheckExamActiveByStudentIDExamID_Result>("ea_spgEA_StudentEnrollmentCheckExamActiveByStudentIDExamID", examIDParameter, studentIDParameter);
        }
    
        public virtual ObjectResult<ea_spEA_StaffRights_Result> ea_spEA_StaffRights(Nullable<decimal> staffID, Nullable<bool> iSRights)
        {
            var staffIDParameter = staffID.HasValue ?
                new ObjectParameter("StaffID", staffID) :
                new ObjectParameter("StaffID", typeof(decimal));
    
            var iSRightsParameter = iSRights.HasValue ?
                new ObjectParameter("ISRights", iSRights) :
                new ObjectParameter("ISRights", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spEA_StaffRights_Result>("ea_spEA_StaffRights", staffIDParameter, iSRightsParameter);
        }
    
        public virtual ObjectResult<ea_spgEA_StudentEnrollmentByExamID_Result> ea_spgEA_StudentEnrollmentByExamID(Nullable<decimal> examID)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spgEA_StudentEnrollmentByExamID_Result>("ea_spgEA_StudentEnrollmentByExamID", examIDParameter);
        }
    
        public virtual int ea_spiEA_StaffRights(Nullable<decimal> staffID, Nullable<bool> iSRights, Nullable<bool> iSAdminRights, Nullable<decimal> assignBy)
        {
            var staffIDParameter = staffID.HasValue ?
                new ObjectParameter("StaffID", staffID) :
                new ObjectParameter("StaffID", typeof(decimal));
    
            var iSRightsParameter = iSRights.HasValue ?
                new ObjectParameter("ISRights", iSRights) :
                new ObjectParameter("ISRights", typeof(bool));
    
            var iSAdminRightsParameter = iSAdminRights.HasValue ?
                new ObjectParameter("ISAdminRights", iSAdminRights) :
                new ObjectParameter("ISAdminRights", typeof(bool));
    
            var assignByParameter = assignBy.HasValue ?
                new ObjectParameter("AssignBy", assignBy) :
                new ObjectParameter("AssignBy", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ea_spiEA_StaffRights", staffIDParameter, iSRightsParameter, iSAdminRightsParameter, assignByParameter);
        }
    
        public virtual ObjectResult<ea_spgEA_StudentEnrollmentandStatusByExamID_Result> ea_spgEA_StudentEnrollmentandStatusByExamID(Nullable<decimal> examID)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spgEA_StudentEnrollmentandStatusByExamID_Result>("ea_spgEA_StudentEnrollmentandStatusByExamID", examIDParameter);
        }
    
        public virtual ObjectResult<ea_spgExamStartFinishStatuByExamID_Result> ea_spgExamStartFinishStatuByExamID(Nullable<decimal> examID)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spgExamStartFinishStatuByExamID_Result>("ea_spgExamStartFinishStatuByExamID", examIDParameter);
        }
    
        public virtual int ea_spiEA_ExamCommentScoreMaster(Nullable<decimal> examID, string qID, Nullable<decimal> studentID, string comment, string scoreType, string obtainScore, Nullable<decimal> commentBy)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            var qIDParameter = qID != null ?
                new ObjectParameter("QID", qID) :
                new ObjectParameter("QID", typeof(string));
    
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(decimal));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var scoreTypeParameter = scoreType != null ?
                new ObjectParameter("ScoreType", scoreType) :
                new ObjectParameter("ScoreType", typeof(string));
    
            var obtainScoreParameter = obtainScore != null ?
                new ObjectParameter("ObtainScore", obtainScore) :
                new ObjectParameter("ObtainScore", typeof(string));
    
            var commentByParameter = commentBy.HasValue ?
                new ObjectParameter("CommentBy", commentBy) :
                new ObjectParameter("CommentBy", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ea_spiEA_ExamCommentScoreMaster", examIDParameter, qIDParameter, studentIDParameter, commentParameter, scoreTypeParameter, obtainScoreParameter, commentByParameter);
        }
    
        public virtual ObjectResult<ea_spgEA_QuestionMasterByExamID_Result> ea_spgEA_QuestionMasterByExamID(Nullable<decimal> examID)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spgEA_QuestionMasterByExamID_Result>("ea_spgEA_QuestionMasterByExamID", examIDParameter);
        }
    
        public virtual ObjectResult<ea_spgEA_QuestionMasterByExamID1_Result> ea_spgEA_QuestionMasterByExamID1(Nullable<decimal> examID)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spgEA_QuestionMasterByExamID1_Result>("ea_spgEA_QuestionMasterByExamID1", examIDParameter);
        }
    
        public virtual ObjectResult<ea_spgEA_ExamMasterByExamID_Result> ea_spgEA_ExamMasterByExamID(Nullable<decimal> examID)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spgEA_ExamMasterByExamID_Result>("ea_spgEA_ExamMasterByExamID", examIDParameter);
        }
    
        public virtual ObjectResult<ea_spgEA_ExamMasterByStaffID_Result> ea_spgEA_ExamMasterByStaffID(Nullable<int> staffID, Nullable<bool> isAdmin)
        {
            var staffIDParameter = staffID.HasValue ?
                new ObjectParameter("StaffID", staffID) :
                new ObjectParameter("StaffID", typeof(int));
    
            var isAdminParameter = isAdmin.HasValue ?
                new ObjectParameter("IsAdmin", isAdmin) :
                new ObjectParameter("IsAdmin", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spgEA_ExamMasterByStaffID_Result>("ea_spgEA_ExamMasterByStaffID", staffIDParameter, isAdminParameter);
        }
    
        public virtual ObjectResult<ea_spgEA_ExamMasterByStaffIdGradeIdAcademicYearID_Result> ea_spgEA_ExamMasterByStaffIdGradeIdAcademicYearID(Nullable<decimal> gradeID, Nullable<decimal> academicYearID, Nullable<decimal> createdBy)
        {
            var gradeIDParameter = gradeID.HasValue ?
                new ObjectParameter("GradeID", gradeID) :
                new ObjectParameter("GradeID", typeof(decimal));
    
            var academicYearIDParameter = academicYearID.HasValue ?
                new ObjectParameter("AcademicYearID", academicYearID) :
                new ObjectParameter("AcademicYearID", typeof(decimal));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spgEA_ExamMasterByStaffIdGradeIdAcademicYearID_Result>("ea_spgEA_ExamMasterByStaffIdGradeIdAcademicYearID", gradeIDParameter, academicYearIDParameter, createdByParameter);
        }
    
        public virtual ObjectResult<ea_spgEA_QuestionMasterByExamIDStudentID_Result> ea_spgEA_QuestionMasterByExamIDStudentID(Nullable<decimal> examID, Nullable<decimal> studentID)
        {
            var examIDParameter = examID.HasValue ?
                new ObjectParameter("ExamID", examID) :
                new ObjectParameter("ExamID", typeof(decimal));
    
            var studentIDParameter = studentID.HasValue ?
                new ObjectParameter("StudentID", studentID) :
                new ObjectParameter("StudentID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ea_spgEA_QuestionMasterByExamIDStudentID_Result>("ea_spgEA_QuestionMasterByExamIDStudentID", examIDParameter, studentIDParameter);
        }
    }
}
