//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NucleusExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCurrentGradeSectionDetails
    {
        public Nullable<decimal> GradeID { get; set; }
        public Nullable<decimal> SectionID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string GradeName { get; set; }
        public string SectionName { get; set; }
        public Nullable<bool> IsVoid { get; set; }
        public Nullable<decimal> StudentID { get; set; }
        public string ProgramName { get; set; }
        public string IsSpecialNeed { get; set; }
        public Nullable<decimal> AcademicYearID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string RollNo { get; set; }
        public string EmergencyContactNo { get; set; }
        public Nullable<bool> ConcentFlag { get; set; }
        public string StudentImage { get; set; }
        public string SchoolEmailID { get; set; }
        public string MothersMobileNo { get; set; }
        public Nullable<bool> Gender { get; set; }
    }
}
