//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NucleusExams
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingStaffList
    {
        public string FullName { get; set; }
        public string ImagePath { get; set; }
        public string ProfilePath { get; set; }
        public Nullable<bool> IsInvalid { get; set; }
        public int StaffMasterID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Salutation { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public bool Sex { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsSystemAccount { get; set; }
        public Nullable<byte> StaffType { get; set; }
        public Nullable<decimal> OrganizationGroupID { get; set; }
        public string AboutMySelf { get; set; }
        public Nullable<int> JobStatus { get; set; }
        public string JobStatusStr { get; set; }
        public string WorkEmail { get; set; }
        public string Expr1 { get; set; }
        public string HRISEmployeeID { get; set; }
        public string TotalWorkExperiance { get; set; }
        public Nullable<decimal> ReportingTo { get; set; }
        public string ReportingToEmail { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public string FoodPriority { get; set; }
        public Nullable<byte> FoodOption { get; set; }
        public string AnyMedicalCondition { get; set; }
        public Nullable<int> NoOfChild { get; set; }
        public string UesDayCare { get; set; }
        public Nullable<bool> AnyCriminalRecord { get; set; }
        public Nullable<bool> SexualMisuseWithMinor { get; set; }
        public string MaritalStatus { get; set; }
        public string Mobile { get; set; }
        public string LegalEntityName { get; set; }
        public string BankName { get; set; }
        public string BankAccountNumber { get; set; }
        public Nullable<bool> IsHDFCBank { get; set; }
        public string BranchName { get; set; }
        public string IFSCCode { get; set; }
        public string NameAsPerBankAccount { get; set; }
        public string CompanyEntityName { get; set; }
    }
}
